# Generated by Django 5.2.4 on 2026-06-03 21:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='member_id',
            field=models.CharField(max_length=20, unique=True, validators=[core.models.validate_member_id]),
        ),
    ]
