# Generated by Django 5.2.4 on 2026-06-04 04:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partymember_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='member_id',
            field=models.CharField(max_length=10, unique=True, validators=[core.models.validate_member_id]),
        ),
    ]
