# Generated by Django 5.2.4 on 2026-06-04 07:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_partymember_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='voters_id',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[core.models.validation_voter_id], verbose_name='Voters ID'),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='ghana_card_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ghana Card'),
        ),
    ]
