# Generated by Django 5.2.4 on 2026-06-04 07:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partymember_voters_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='voters_id',
            field=models.CharField(blank=True, max_length=10, validators=[core.models.validation_voter_id], verbose_name='Voters ID'),
        ),
    ]
