# Generated by Django 5.2.4 on 2026-06-07 01:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_partymember_voters_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.models.validation_phone_no]),
        ),
    ]
