# Generated by Django 5.2.4 on 2026-06-07 01:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_partymember_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='ghana_card_id',
            field=models.CharField(blank=True, max_length=15, validators=[core.models.validation_ghana_card], verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[core.models.validation_phone_no]),
        ),
    ]
