# Generated by Django 5.2.4 on 2026-06-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_partymember_ghana_card_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='electoral_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='core.electoralarea'),
        ),
    ]
