# Generated by Django 5.2.4 on 2026-06-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_electoralarea_pollingstation_electoral_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoralarea',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='electoralarea',
            name='constituency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electoralarea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electoralarea',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='electoral_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.electoralarea'),
        ),
    ]
